ALTER TYPE "OutboxEventType" ADD VALUE IF NOT EXISTS 'PAYMENT_VALIDATED';
ALTER TYPE "OutboxEventType" ADD VALUE IF NOT EXISTS 'PAYMENT_VALIDATION_FAILED';
ALTER TYPE "OutboxEventType" ADD VALUE IF NOT EXISTS 'PAYMENT_RESERVED';
ALTER TYPE "OutboxEventType" ADD VALUE IF NOT EXISTS 'PAYMENT_SETTLED';
ALTER TYPE "OutboxEventType" ADD VALUE IF NOT EXISTS 'PAYMENT_RETURNED';

ALTER TABLE "OutboxEvent" ADD COLUMN "eventKey" TEXT NOT NULL DEFAULT gen_random_uuid()::text;
CREATE UNIQUE INDEX "OutboxEvent_eventKey_key" ON "OutboxEvent"("eventKey");
